# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import get_package_paths

block_cipher = None
# Just use this to get the site-packages directory for python-snappy dlls we need.
snappy_libs = get_package_paths('setuptools')[0] + "python_snappy.libs"

a = Analysis(['..\\afflux_gui.py'],
             pathex=[],
             binaries=[],
             datas=[('..\\plugins\\disk_image.py', '.\\plugins'),
                    ('..\\plugins\\android_adb.py', '.\\plugins'),
                    ('..\\plugins\\usb_drive.py', '.\\plugins'),
                    ('..\\plugins\\apple_afc.py', '.\\plugins'),
                    ('..\\plugins\\generic_ftp.py', '.\\plugins'),
                    ('..\\plugins\\generic_smb.py', '.\\plugins'),
                    ('..\\plugins\\generic_ssh.py', '.\\plugins'),
                    ('..\\plugins\\ios_ssh.py', '.\\plugins'),
                    ('..\\plugins\\generic_http.py', '.\\plugins'),
                    ('..\\gui\\afflux_gui_ui.py', '.\\gui'),
                    ('..\\gui\\afflux_gui_threads.py', '.\\gui'),
                    ('..\\gui\\breeze_resources.py', '.\\gui'),
                    ('..\\gui\\splash.png', '.\\gui'),
                    (snappy_libs, '.\\python_snappy.libs')],
             hiddenimports=['adb_shell.adb_device',
                            'adb_shell.transport.usb_transport',
                            'adb_shell.auth.keygen',
                            'adb_shell.auth.sign_pythonrsa',
                            'adb_shell.exceptions',
                            'pymobiledevice3.lockdown',
                            'pymobiledevice3.services.afc',
                            'pysftp',
                            'smbprotocol',
                            'smbclient',
                            'bs4',
                            'requests',
                            'imaging',
                            'plugin_manager',
                            'utilities',
                            'gui.afflux_gui_ui',
                            'gui.afflux_gui_threads',
                            'gui.breeze_resources',
                            'PyQt5.QtCore',
                            'PyQt5.QtGui',
                            'PyQt5.QtWidgets',
                            'PyQt5.QtWebEngineWidgets'],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=['tkinter', 'tcl'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
splash = Splash('..\\gui\\splash.png',
                binaries=a.binaries,
                datas=a.datas,
                text_pos=None,
                text_size=12,
                minify_script=True)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          splash,
          splash.binaries,
          [],
          name='afflux_gui',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None , icon='..\\gui\\command.ico')
